SERVER_IP   = "192.168.56.10"
SERVER_NAME = "davgalleS"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant",
    type: "rsync",
    rsync__exclude: [".git/", ".vagrant/"]

  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider "virtualbox" do |v|
      v.name   = SERVER_NAME
      v.memory = 8192
      v.cpus   = 4
    end
    server.vm.provision "shell", path: "scripts/install.sh"
    server.vm.provision "shell", path: "scripts/launch.sh"
  end
end